name: Publicar Defecation Journal

on:
  schedule:
    - cron: '0 6 * * *'
    - cron: '0 14 * * *'
    - cron: '0 20 * * *'
  workflow_dispatch:

permissions:
  contents: write  # Necesario para hacer git push

jobs:
  publicar:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar script
        run: |
          python defecation_journal_bot.py

      - name: Commit historial actualizado
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add historial_noticias.json
          git commit -m "Actualizar historial de noticias" || echo "Sin cambios"
          git push
